version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    volumes:
      - kibana_config:/usr/share/kibana/config
      - kibana_data:/usr/share/kibana/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./http-requests.log:/usr/src/app/http-requests.log
    networks:
      - elastic
    depends_on:
      - logstash
    command: ["filebeat", "-e"]

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.14.0
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - elastic
    depends_on:
      - elasticsearch
    command: ["metricbeat", "-e", "-system.hostfs=/hostfs"]

  myapp:
    build: .
    environment:
      - NODE_PATH=/usr/src/app/node_modules
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
    networks:
      - elastic

volumes:
  esdata:
  kibana_config:
  kibana_data:

networks:
  elastic:
    driver: bridge
